-- Database Design
-- STATIC_PAGES
-- - ID: ABOUT_US, CONTACT_US
-- - CONTENT
--
-- PRODUCTS:
-- - ID
-- - NAME
-- - DESCRIPTION
--
-- TESTIMONIES:
-- - ID
-- - NAME
-- - PHOTO
-- - CONTENT
--
-- RESI:
-- - ID
-- - CONTENT

-- Create database and select it
CREATE DATABASE LOLLYPOPSTUFF88;
-- CREATE DATABASE u412990950_lolly;

USE LOLLYPOPSTUFF88;
-- USE u412990950_lolly

-- Create tables
CREATE TABLE USERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
)ENGINE=INNODB;

CREATE TABLE SLIDESHOWS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    URL VARCHAR(1000)
)ENGINE=INNODB;

/*
CREATE TABLE STATIC_PAGES(
    ID VARCHAR(10) PRIMARY KEY,
    CONTENT TEXT
)ENGINE=INNODB;
*/

CREATE TABLE PRODUCTS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    IMAGE VARCHAR(1000),
    DESCRIPTION TEXT
)ENGINE=INNODB;

CREATE TABLE TESTIMONIES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    URL VARCHAR(1000)
)ENGINE=INNODB;

CREATE TABLE RESI(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT TEXT
)ENGINE=INNODB;

-- Initialization USERS table
INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES(1, 'via.lolipop', md5('a0a0a0'));
INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES(2, 'test', md5('test'));

-- Initialization STATIC_PAGES table
-- INSERT INTO STATIC_PAGES(ID) VALUES('ABOUT_US');
-- INSERT INTO STATIC_PAGES(ID) VALUES('CONTACT_US');
-- INSERT INTO STATIC_PAGES(ID) VALUES('HOW_TO_BUY');

-- Initialization RESI table
INSERT INTO RESI(ID) VALUES(1);